#!/usr/bin/env python3
"""
openEuler ROS Repository Helper (GitCode/AtomGit V5 API)

This script provides fallback actions for edge cases:
1. Creating a brand new personal repository when an upstream doesn't exist.
2. Forking repositories from non-official orgs.
3. Managing specific PRs (like updating titles).

Usage:
  python3 git_helper.py create-repo --name test [--domain atomgit.com]
  python3 git_helper.py fork-repo --owner ib_robot --repo pymoveit2 [--domain atomgit.com]
  python3 git_helper.py update-pr --owner src-openeuler --repo moveit_msgs --pr 7 --title "[WIP] ..." [--domain atomgit.com]
"""

import os
import json
import urllib.request
import urllib.parse
from pathlib import Path
import re
import argparse
import sys

def get_token():
    """Retrieve API token from ~/.config/gitcode (works for both GitCode and AtomGit)"""
    token_file = Path(os.path.expanduser("~/.config/gitcode"))
    if not token_file.exists():
        print(f"Error: Token file not found at {token_file}")
        sys.exit(1)
        
    with open(token_file, "r") as f:
        content = f.read()
        match = re.search(r"token:\s*(.+)", content)
        if not match:
            print("Error: Could not parse token from config file")
            sys.exit(1)
        return match.group(1).strip()

class GitV5Client:
    def __init__(self, token, domain="gitcode.com"):
        self.token = token
        self.base_url = f"https://{domain}/api/v5"
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
            "User-Agent": "ros-oe-helper/1.0"
        }

    def _request(self, endpoint, method="GET", data=None):
        url = f"{self.base_url}/{endpoint.lstrip('/')}"
        req_data = json.dumps(data).encode("utf-8") if data else None
        req = urllib.request.Request(url, data=req_data, headers=self.headers, method=method)
        
        try:
            with urllib.request.urlopen(req) as response:
                content = response.read().decode("utf-8")
                return json.loads(content) if content else {}
        except urllib.error.HTTPError as e:
            error_content = e.read().decode("utf-8")
            try:
                err_json = json.loads(error_content)
                err_msg = err_json.get("message") or err_json.get("error_message") or error_content
            except:
                err_msg = error_content
            print(f"HTTP {e.code}: {err_msg}")
            sys.exit(1)
        except Exception as e:
            print(f"Request failed: {str(e)}")
            sys.exit(1)

    def create_personal_repo(self, name, description="", private=False):
        """Create a new personal repository"""
        data = {
            "name": name,
            "description": description,
            "private": private,
            "auto_init": True
        }
        return self._request("user/repos", method="POST", data=data)

    def fork_repo(self, owner, repo):
        """Fork any repository"""
        return self._request(f"repos/{owner}/{repo}/forks", method="POST")

    def update_pr(self, owner, repo, pr_number, title=None, body=None):
        """Update PR title/description"""
        data = {}
        if title:
            data["title"] = title
        if body:
            data["body"] = body
        return self._request(f"repos/{owner}/{repo}/pulls/{pr_number}", method="PATCH", data=data)


def main():
    parser = argparse.ArgumentParser(description="Git V5 Helper for Edge Cases")
    parser.add_argument("--domain", default="atomgit.com", help="Domain (e.g. atomgit.com or gitcode.com)")
    
    subparsers = parser.add_subparsers(dest="action", help="Action to perform")
    
    # Create Repo Subcommand
    create_parser = subparsers.add_parser("create-repo", help="Create a new personal repo")
    create_parser.add_argument("--name", required=True, help="Repository name")
    create_parser.add_argument("--desc", default="Autogenerated by openEuler ROS workflow", help="Description")
    create_parser.add_argument("--private", action="store_true", help="Make it private")
    
    # Fork Repo Subcommand
    fork_parser = subparsers.add_parser("fork-repo", help="Fork a repository")
    fork_parser.add_argument("--owner", required=True, help="Original owner (e.g. ib_robot)")
    fork_parser.add_argument("--repo", required=True, help="Repository name")
    
    # Update PR Subcommand
    update_parser = subparsers.add_parser("update-pr", help="Update a PR")
    update_parser.add_argument("--owner", required=True, help="Target repository owner")
    update_parser.add_argument("--repo", required=True, help="Target repository name")
    update_parser.add_argument("--pr", required=True, type=int, help="PR number")
    update_parser.add_argument("--title", help="New PR Title")
    update_parser.add_argument("--desc", help="New PR Description")
    
    args = parser.parse_args()
    if not args.action:
        parser.print_help()
        sys.exit(1)
        
    client = GitV5Client(get_token(), domain=args.domain)
    
    if args.action == "create-repo":
        print(f"🚀 Creating personal repository '{args.name}' on {args.domain}...")
        res = client.create_personal_repo(args.name, args.desc, args.private)
        print(f"🎉 Success: {res.get('html_url')}")
        
    elif args.action == "fork-repo":
        print(f"🚀 Forking {args.owner}/{args.repo} to your account on {args.domain}...")
        res = client.fork_repo(args.owner, args.repo)
        print(f"🎉 Success! Fork created: {res.get('full_name')} at {res.get('html_url')}")
        
    elif args.action == "update-pr":
        if not args.title and not args.desc:
            print("❌ Must provide --title or --desc")
            sys.exit(1)
        print(f"🚀 Updating PR #{args.pr} on {args.owner}/{args.repo} ({args.domain})...")
        res = client.update_pr(args.owner, args.repo, args.pr, title=args.title, body=args.desc)
        print(f"🎉 Success! PR updated: {res.get('html_url')}")

if __name__ == "__main__":
    main()
