%bcond_without tests
%bcond_without weak_deps

%define pkg_name         ROS_PACKAGE_NAME

Name:           ros-%{ros_distro}-%{pkg_name}
Version:        ROS_PACKAGE_VERSION
Release:        ROS_PACKAGE_RELEASE%{?dist}%{?release_suffix}
Summary:        Third-party package %{pkg_name}

Url:            ROS_PACKAGE_URL
License:        ROS_PACKAGE_LICENSE
Source0:        %{pkg_name}-%{version}.tar.gz
ROS_SOURCE_FIX

# 基础构建依赖
BuildRequires:  cmake3
BuildRequires:  gcc-c++
BuildRequires:  make

# 可选的测试依赖
%if 0%{?with_tests}
BuildRequires:  gtest-devel
%endif

# 自定义依赖（通过spec_fix添加）
ROS_PACKAGE_BUILDREQUIRES

# 运行时依赖
ROS_PACKAGE_REQUIRES

%description
Third-party package %{pkg_name} for ROS %{ros_distro}

%prep
%autosetup -c -n %{name}-%{version}
ROS_PREP_FIX

%build
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/%{ros_distro}" \
    -DCMAKE_BUILD_TYPE=Release \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ROS_CMAKE_ARGS_FIX \
    ../%{pkg_name}-%{version}

%make_build

%install
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
cd .obj-%{_target_platform}
# 运行测试
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build test || echo "RPM TESTS FAILED"
%endif

%files
/opt/ros/%{ros_distro}

%changelog
* ROS_PACKAGE_CHANGELOG
- Autogenerated by ros-oe-upstream-init